# Generated by Django 3.2 on 2022-05-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permis_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='codePermis',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='demande',
            name='statut',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
