# Generated by Django 3.2 on 2022-05-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permis_app', '0002_auto_20220514_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='Employeur',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
