# Generated by Django 3.2 on 2022-05-16 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permis_app', '0005_infraction_permis_travailleur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travailleur',
            name='id_Infra',
        ),
        migrations.RemoveField(
            model_name='travailleur',
            name='id_permis',
        ),
        migrations.AddField(
            model_name='infraction',
            name='id_trvl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='permis_app.travailleur'),
        ),
        migrations.AddField(
            model_name='permis',
            name='id_trvl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='permis_app.travailleur'),
        ),
        migrations.AddField(
            model_name='permis',
            name='renouveler',
            field=models.BooleanField(default=False),
        ),
    ]
