# Generated by Django 3.2 on 2022-05-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permis_app', '0007_hystorique'),
    ]

    operations = [
        migrations.AddField(
            model_name='hystorique',
            name='type_user',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
