# Generated by Django 3.2 on 2022-05-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permis_app', '0008_hystorique_type_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societe',
            name='gmail',
            field=models.EmailField(max_length=250, null=True),
        ),
    ]
