# Generated by Django 3.2 on 2022-05-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permis_app', '0009_alter_societe_gmail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='TypeDemande',
            field=models.CharField(choices=[('Nouvaux', 'Nouvaux'), ('renouvellement', 'renouvellement')], default='Nouvaux', max_length=250),
        ),
    ]
