# Generated by Django 3.2 on 2022-05-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permis_app', '0010_alter_demande_typedemande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='codePermis',
            field=models.IntegerField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
