# Generated by Django 3.2 on 2022-05-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permis_app', '0011_alter_demande_codepermis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='cnss',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='demande',
            name='codePermis',
            field=models.IntegerField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='demande',
            name='email',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='demande',
            name='numIMM',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='demande',
            name='numPass',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='demande',
            name='numTel',
            field=models.IntegerField(),
        ),
    ]
