# Generated by Django 3.2 on 2022-05-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permis_app', '0012_auto_20220526_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permis',
            name='TypePermis',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
