# Generated by Django 3.2 on 2022-05-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permis_app', '0014_alter_demande_etatretrait'),
    ]

    operations = [
        migrations.AddField(
            model_name='permis',
            name='codePermis',
            field=models.IntegerField(default=23, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='demande',
            name='codePermis',
            field=models.IntegerField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
