# Generated by Django 3.2 on 2022-05-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permis_app', '0015_auto_20220526_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permis',
            name='TypePermis',
            field=models.CharField(max_length=250),
        ),
    ]
